server:
  name: violin-retail
  addr: "0.0.0.0:8081"

zap:
  debugFileName: "E:\\log\\violin-api\\debug.log"
  infoFileName: "E:\\log\\violin-api\\info.log"
  warnFileName: "E:\\log\\violin-api\\warn.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

redis:
  network: "tcp"
  addr: "localhost:6379"
  password: "123456"
  db: 3

mongo:
  host: "localhost"
  port: 27017